---
- name: "Apache installation using docker"
  hosts: prod
  become : true
  
  pre_tasks: 
    - name: install EPEL repo
      package: 
        name: epel-release
        state: present
      when: ansible_distribution=="CentOS"
    - name: install python-pip
      yum: 
        name: python-pip 
        state: present
        update_cache: yes
    - name : Install docker python 
      pip: 
        name: docker-py
    - name : install git 
      pip:
        name: '{{item}}'
        state: present
      when: ansible_distribution== "CentOS"
      loop:
        - gitpython 
        - wget

  tasks:
   - name : generate html
     template:
       src: "index.html"
       dest: /home/vagrant/index.html
    
   - name: Create Apache container
     docker_container:
       name: webapp
       image: httpd
       ports:
         - "80:80"
       volumes:
         - /home/vagrant/index.html:/usr/local/apache2/htdocs/index.html
